version: '1.6'

services:
  app:
    image: 192.168.3.7:3000/node-app:1.6
    container_name: node-app
    pull_policy: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"