version: '1.6'

services:
  app:
    image: 192.168.3.7:3000/node-app:1.6
    container_name: node-app
    pull_policy: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password   # Make sure to match with MySQL config below
      - MYSQL_DATABASE=myapp  
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: